trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - '*'
    - src/libraries/System.Private.CoreLib/*
    exclude:
    - docs/*
    - CODE-OF-CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - SECURITY.md
    - THIRD-PARTY-NOTICES.TXT
    - src/installer/*
    - src/libraries/*
    - eng/pipelines/installer/*
    - eng/pipelines/libraries/*


pr:
  branches:
    include:
    - master
  paths:
    exclude: # don't trigger the CI if only a doc file was changed
    - docs/*
    - eng/common/README.md
    - src/benchmarks/micro/Serializers/README.md
    - src/benchmarks/micro/README.md
    - src/benchmarks/real-world/JitBench/README.md
    - src/benchmarks/real-world/Microsoft.ML.Benchmarks/Input/README.md
    - src/tools/ResultsComparer/README.md
    - README.md

jobs:
#
# Checkout repository
#
- template: /eng/pipelines/common/checkout-job.yml

- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/common/build-coreclr-and-libraries-job.yml
    buildConfig: release
    platforms:
    - Linux_x64
    - Windows_NT_x64
    - Windows_NT_x86
    jobParameters:
      testGroup: perf
    
- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/coreclr/templates/perf-job.yml
    buildConfig: release
    platforms:
    - Linux_x64
    - Windows_NT_x64
    - Windows_NT_x86
    jobParameters:
      testGroup: perf
      liveLibrariesBuildConfig: Release
